[entities]
Chemical_and_drugs
strength
form
route
dosage
Frequency
Date
Duration
BIO_comp
DISO
BIO_milieu
BIO
Constantes
!SECTION_
	SECTION_examen_complementaire
	SECTION_conclusion
	SECTION_motif
	SECTION_antecedent
	SECTION_head
	SECTION_traitement_entree
	SECTION_traitement_sortie
	SECTION_evolution
	SECTION_antecedent_familiaux
	SECTION_histoire
	SECTION_traitement
	SECTION_examen_clinique
	SECTION_autre
	SECTION_mode_de_vie

[attributes]
Action      Arg:Chemical_and_drugs, Value:Start|Stop|Increase|Decrease|OtherChange|UniqueDose|Unknown
Certainty      Arg:Chemical_and_drugs|DISO, Value:Certain|Hypothetical|Conditional|Unknown
Temporality      Arg:Chemical_and_drugs, Value:Past|Present|Future|Unknown
Negation      Arg:Chemical_and_drugs|DISO
Allergie      Arg:Chemical_and_drugs
Family      Arg:Chemical_and_drugs|DISO
AttDate      Arg:Date|Duration, Value:StartDate|StopDate|IntermediateDate|Unknown
RefTemp      Arg:Date|Duration, Value:Relative|Absolute|Unknown

[relations]
Depend      Arg1:Chemical_and_drugs, Arg2:strength|form|route|dosage|Frequency|Date|Duration
<OVERLAP> Arg1:<ANY>, Arg2:<ANY>, <OVL-TYPE>:contain|equal|cross

[events]
