[labels]
BIO  | BIO
BIO_comp  | BIO_comp
Chemical_and_drugs | Chemical_and_drugs
SECTION_examen_complementaire | SECTION_examen_complementaire
SECTION_conclusion | SECTION_conclusion
SECTION_motif | SECTION_motif
SECTION_antecedent | SECTION_antecedent
SECTION_head | SECTION_head
SECTION_traitement_entree | SECTION_traitement_entree
SECTION_traitement_sortie | SECTION_traitement_sortie
SECTION_evolution | SECTION_evolution
SECTION_antecedent_familiaux | SECTION_antecedent_familiaux
SECTION_histoire | SECTION_histoire
SECTION_traitement | SECTION_traitement
SECTION_examen_clinique | SECTION_examen_clinique
SECTION_autre | SECTION_autre
SECTION_mode_de_vie | SECTION_mode_de_vie
DISO | DISO
CONST | Constantes
Date | Date
Freq | Frequency
Duration | Duration
Dose | dosage
Strength | strength
Form | form
Route | route

[drawing]
Chemical_and_drugs	bgColor:#74aff3
DISO	bgColor:#ecaaae
SECTION_examen_complementaire	bgColor:#17becf
SECTION_conclusion	bgColor:#17becf
SECTION_motif	bgColor:#17becf
SECTION_antecedent	bgColor:#17becf
SECTION_head	bgColor:#17becf
SECTION_traitement_entree	bgColor:#17becf
SECTION_traitement_sortie	bgColor:#17becf
SECTION_evolution	bgColor:#17becf
SECTION_antecedent_familiaux	bgColor:#17becf
SECTION_histoire	bgColor:#17becf
SECTION_traitement	bgColor:#17becf
SECTION_examen_clinique	bgColor:#17becf
SECTION_autre	bgColor:#17becf
SECTION_mode_de_vie	bgColor:#17becf
BIO bgColor:#01a46a
BIO_comp	bgColor:#96c99e
BIO_milieu	bgColor:#c54600
Constantes	bgColor:#ffa835
dosage	bgColor:#b59cd0
form	bgColor:#ffa5f5
strength	bgColor:#ff4c9c
route	bgColor:#e37bff
Date	bgColor:#ff5c57
Duration	bgColor:#abd286
Frequency	bgColor:#e1a688

ARC_DEFAULT	color:red, dashArray:-, arrowHead:triangle-8
